[versions]
agp = "8.7.2"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.10.0"
gson = "2.10.1"
http = "4.11.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
gson = { group = "com.google.code.gson", name = "gson", version.ref="gson" }
http = { group = "com.squareup.okhttp3", name = "okhttp", version.ref="http" }
logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "http"}

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

